name: LifestealPlugin
main: net.uniloftsky.nukkit.lifesteal.LifestealPlugin
version: "${pom.version}"
api: [ "1.0.0" ]
author: uniloftsky
description: Lifesteal plugin
permissions:
  uniloftsky.nukkit.lifesteal:
    default: op